// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright 2018-2022 NXP
 *
 */

#define CONFIG_MASTER_CORE                     0
#define CONFIG_SLAVE_FIRST_CORE                 1

/* set Master core size to 512M, slave core size to 256M, share mem to 256M */

/* Number of cores in each cluster */
#define CORE_NUM_PER_CLUSTER    4
#define CONFIG_MAX_CPUS  4

#define CONFIG_ARP_TIMEOUT     200UL

/*reserve 5MB memory for sp i.e. */
#define CONFIG_SYS_STACK_RESERVE_LEN  (CONFIG_SYS_MALLOC_LEN + (5 * SZ_1M))

#define CONFIG_SYS_DDR_SDRAM_SLAVE_RESERVE_SIZE (SZ_32M)
#define CONFIG_SYS_DDR_SDRAM_SHARE_RESERVE_SIZE (SZ_4M)
#define CONFIG_SYS_DDR_SDRAM_SLAVE_SIZE        (SZ_32M)
#define CONFIG_SYS_DDR_SDRAM_SLAVE_ADDR (0x60000000)

#define CONFIG_SYS_DDR_SDRAM_SLAVE_COREX_ADDR(coreid) \
	(CONFIG_SYS_DDR_SDRAM_SLAVE_ADDR + \
	(coreid - 1) * CONFIG_SYS_DDR_SDRAM_SLAVE_SIZE)
#define CONFIG_SYS_DDR_SDRAM_SLAVE_COREX_RAMTOP_ADDR(coreid) \
	(CONFIG_SYS_DDR_SDRAM_SLAVE_ADDR + \
	(coreid - 1) * CONFIG_SYS_DDR_SDRAM_SLAVE_SIZE + \
	CONFIG_SYS_MALLOC_LEN + CONFIG_SYS_STACK_RESERVE_LEN )

#define CONFIG_SYS_DDR_SDRAM_SHARE_SIZE \
	(CONFIG_SYS_DDR_SDRAM_SLAVE_RESERVE_SIZE - \
	CONFIG_SYS_DDR_SDRAM_SHARE_RESERVE_SIZE)
#define CONFIG_SYS_DDR_SDRAM_SHARE_BASE \
	(CONFIG_SYS_DDR_SDRAM_SLAVE_ADDR + \
	CONFIG_SYS_DDR_SDRAM_SLAVE_SIZE*(CONFIG_MAX_CPUS-1))

#define CONFIG_SYS_DDR_SDRAM_SHARE_RESERVE_BASE \
	(CONFIG_SYS_DDR_SDRAM_SHARE_BASE + CONFIG_SYS_DDR_SDRAM_SHARE_SIZE)

#define CONFIG_GICV3

/* GICv3 base address */
#define GICD_BASE          0x38800000
#define GICR_BASE          0x38880000