// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright 2023 NXP
 *
 */

#ifndef _IMX93_BAREMETAL_H_
#define _IMX93_BAREMETAL_H_

/* Number of cores in each cluster */
#define CORE_NUM_PER_CLUSTER    2
#define CONFIG_MAX_CPUS         2

#define CONFIG_GICV3

/* GICv3 base address */
#define GICD_BASE          0x48000000
#define GICR_BASE          0x48040000

#if defined(CONFIG_BAREMETAL)

#define CONFIG_BAREMETAL_FIRST_CORE 0

#define CONFIG_ARP_TIMEOUT     200UL

/* set Master core size to 768M, slave core to 32M, share mem to 32M */
#define CONFIG_BAREMETAL_SYS_SDRAM_MASTER_SIZE  (768 * 1024 * 1024UL)
#define CONFIG_BAREMETAL_SYS_SDRAM_SLAVE_SIZE   (32 * 1024 * 1024UL)
#define CONFIG_BAREMETAL_SYS_SDRAM_RESERVE_SIZE (4 * 1024 * 1024UL)
#define CONFIG_BAREMETAL_SYS_SDRAM_SHARE_SIZE \
	((32 * 1024 * 1024UL) - CONFIG_BAREMETAL_SYS_SDRAM_RESERVE_SIZE)
#define CONFIG_BAREMETAL_SYS_SDRAM_SHARE_BASE \
	(CONFIG_SYS_SDRAM_BASE + CONFIG_BAREMETAL_SYS_SDRAM_MASTER_SIZE \
	+ CONFIG_BAREMETAL_SYS_SDRAM_SLAVE_SIZE * (CONFIG_MAX_CPUS - 1))
#define CONFIG_BAREMETAL_SYS_SDRAM_RESERVE_BASE \
	(CONFIG_BAREMETAL_SYS_SDRAM_SHARE_BASE + \
	CONFIG_BAREMETAL_SYS_SDRAM_SHARE_SIZE)

#if defined(CONFIG_BAREMETAL_SLAVE_MODE)

#undef CONFIG_EXTRA_ENV_SETTINGS

#undef CONFIG_ETHPRIME
#define CONFIG_ETHPRIME                 "eth0"

#endif /* CONFIG_BAREMETAL_SLAVE_MODE */

#endif /* CONFIG_BAREMETAL */

#endif /* _IMX93_BAREMETAL_H_ */
